/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WMSdataStructuresProject;

import java.util.Date;

/**
 *
 * @author User
 */
public class Ceo extends javax.swing.JFrame {

    Company c = new Company();
    String name;

    public Ceo() {
        initComponents();
    }

    public Ceo(Company c, String n) {
        this.name = n;
        initComponents();
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameFielf7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane22 = new javax.swing.JScrollPane();
        cInfoTextArea = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        ctasksTextArea = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        ceTextArea = new javax.swing.JTextArea();
        passButton7 = new javax.swing.JButton();
        outButton7 = new javax.swing.JButton();
        completedButton7 = new javax.swing.JButton();
        tasksButton = new javax.swing.JButton();
        hierarchyBTN = new javax.swing.JButton();
        detailsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        kickbutton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        mnameField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        showDlgBTN = new javax.swing.JButton();
        ebtn = new javax.swing.JButton();
        newNameField = new javax.swing.JTextField();
        newRoleField = new javax.swing.JTextField();
        newDepField = new javax.swing.JTextField();
        newPassField = new javax.swing.JTextField();
        newSalField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        titleBTN = new javax.swing.JTextField();
        dateBTN = new javax.swing.JTextField();
        SendBTN = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        dlgBTN = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        mtasksbtn = new javax.swing.JButton();
        mdetailsbtn = new javax.swing.JButton();
        getdlgbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameFielf7.setBackground(new java.awt.Color(0, 102, 102));
        nameFielf7.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WMSdataStructuresProject/reslogo.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Aldhabi", 0, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("WMS");

        jLabel25.setFont(new java.awt.Font("Aldhabi", 1, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Welcome CEO "+name);

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));
        jPanel8.setForeground(new java.awt.Color(102, 102, 102));

        cInfoTextArea.setColumns(20);
        cInfoTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        cInfoTextArea.setRows(5);
        jScrollPane22.setViewportView(cInfoTextArea);

        ctasksTextArea.setColumns(20);
        ctasksTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ctasksTextArea.setRows(5);
        jScrollPane23.setViewportView(ctasksTextArea);

        ceTextArea.setColumns(20);
        ceTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        ceTextArea.setRows(5);
        jScrollPane24.setViewportView(ceTextArea);

        passButton7.setBackground(new java.awt.Color(0, 102, 102));
        passButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passButton7.setForeground(new java.awt.Color(255, 255, 255));
        passButton7.setText("pass a day");
        passButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passButton7MouseClicked(evt);
            }
        });
        passButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passButton7ActionPerformed(evt);
            }
        });

        outButton7.setBackground(new java.awt.Color(0, 102, 102));
        outButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        outButton7.setForeground(new java.awt.Color(255, 255, 255));
        outButton7.setText("Log out");
        outButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outButton7MouseClicked(evt);
            }
        });

        completedButton7.setBackground(new java.awt.Color(0, 102, 102));
        completedButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        completedButton7.setForeground(new java.awt.Color(255, 255, 255));
        completedButton7.setText("Complete current task");
        completedButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(passButton7)
                        .addGap(27, 27, 27)
                        .addComponent(completedButton7)
                        .addGap(27, 27, 27)
                        .addComponent(outButton7))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passButton7)
                    .addComponent(outButton7)
                    .addComponent(completedButton7))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        tasksButton.setBackground(new java.awt.Color(0, 153, 153));
        tasksButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tasksButton.setForeground(new java.awt.Color(255, 255, 255));
        tasksButton.setText("Tasks");
        tasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksButtonActionPerformed(evt);
            }
        });

        hierarchyBTN.setBackground(new java.awt.Color(0, 153, 153));
        hierarchyBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hierarchyBTN.setForeground(new java.awt.Color(255, 255, 255));
        hierarchyBTN.setText("Show");
        hierarchyBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hierarchyBTNActionPerformed(evt);
            }
        });

        detailsButton.setBackground(new java.awt.Color(0, 153, 153));
        detailsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        detailsButton.setForeground(new java.awt.Color(255, 255, 255));
        detailsButton.setText("Details");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informations about you:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Company Hierarchy:");

        kickbutton.setBackground(new java.awt.Color(0, 153, 153));
        kickbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kickbutton.setForeground(new java.awt.Color(255, 255, 255));
        kickbutton.setText("Kick prev.");
        kickbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kickbuttonActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Add new manager's details:");

        addBTN.setBackground(new java.awt.Color(0, 153, 153));
        addBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBTN.setForeground(new java.awt.Color(255, 255, 255));
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("---------------------------------------------------------------------------------------------");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("--------------------------------------------------------------------------------------------");

        mnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnameFieldActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Manager's name:");

        showDlgBTN.setBackground(new java.awt.Color(0, 153, 153));
        showDlgBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        showDlgBTN.setForeground(new java.awt.Color(255, 255, 255));
        showDlgBTN.setText("Dlg. Tasks");
        showDlgBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDlgBTNActionPerformed(evt);
            }
        });

        ebtn.setBackground(new java.awt.Color(0, 153, 153));
        ebtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ebtn.setForeground(new java.awt.Color(255, 255, 255));
        ebtn.setText("Employees");
        ebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebtnActionPerformed(evt);
            }
        });

        newNameField.setText("enter name..");

        newRoleField.setText("enter role..");
        newRoleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoleFieldActionPerformed(evt);
            }
        });

        newDepField.setText("enter department..");

        newPassField.setText("enter password..");

        newSalField.setText("Enter salary..");
        newSalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSalFieldActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Send task to manager:");

        titleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleBTNActionPerformed(evt);
            }
        });

        dateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateBTNActionPerformed(evt);
            }
        });

        SendBTN.setBackground(new java.awt.Color(0, 153, 153));
        SendBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SendBTN.setForeground(new java.awt.Color(255, 255, 255));
        SendBTN.setText("Send");
        SendBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBTNActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("title");

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("due Date");

        dlgBTN.setBackground(new java.awt.Color(0, 153, 153));
        dlgBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dlgBTN.setForeground(new java.awt.Color(255, 255, 255));
        dlgBTN.setText("Show");
        dlgBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlgBTNActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText(" delegated tasks:");

        mtasksbtn.setBackground(new java.awt.Color(0, 153, 153));
        mtasksbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mtasksbtn.setForeground(new java.awt.Color(255, 255, 255));
        mtasksbtn.setText("Tasks");
        mtasksbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtasksbtnActionPerformed(evt);
            }
        });

        mdetailsbtn.setBackground(new java.awt.Color(0, 153, 153));
        mdetailsbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mdetailsbtn.setForeground(new java.awt.Color(255, 255, 255));
        mdetailsbtn.setText("Details");
        mdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mdetailsbtnActionPerformed(evt);
            }
        });

        getdlgbtn.setBackground(new java.awt.Color(0, 153, 153));
        getdlgbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getdlgbtn.setForeground(new java.awt.Color(255, 255, 255));
        getdlgbtn.setText("Get dlg. Tasks");
        getdlgbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdlgbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nameFielf7Layout = new javax.swing.GroupLayout(nameFielf7);
        nameFielf7.setLayout(nameFielf7Layout);
        nameFielf7Layout.setHorizontalGroup(
            nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFielf7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(hierarchyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(nameFielf7Layout.createSequentialGroup()
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielf7Layout.createSequentialGroup()
                        .addContainerGap(5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(nameFielf7Layout.createSequentialGroup()
                                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameFielf7Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel31)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(nameFielf7Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(showDlgBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(ebtn)
                                        .addGap(41, 41, 41)
                                        .addComponent(getdlgbtn))
                                    .addGroup(nameFielf7Layout.createSequentialGroup()
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(newRoleField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(nameFielf7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(mtasksbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(mdetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielf7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32)
                        .addGap(31, 31, 31)
                        .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameFielf7Layout.createSequentialGroup()
                                .addComponent(dateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SendBTN))
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(nameFielf7Layout.createSequentialGroup()
                        .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameFielf7Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(newDepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(newSalField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(nameFielf7Layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(nameFielf7Layout.createSequentialGroup()
                                            .addComponent(jLabel35)
                                            .addGap(117, 117, 117)
                                            .addComponent(dlgBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel26)
                                        .addGroup(nameFielf7Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(detailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(27, 27, 27)
                                            .addComponent(tasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(nameFielf7Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(nameFielf7Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielf7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kickbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        nameFielf7Layout.setVerticalGroup(
            nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFielf7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameFielf7Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26))
                    .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(nameFielf7Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(hierarchyBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(detailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(dlgBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(mnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showDlgBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getdlgbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mdetailsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mtasksbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newRoleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kickbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGroup(nameFielf7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(titleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendBTN))
                .addGap(115, 115, 115))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameFielf7, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameFielf7, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passButton7MouseClicked
        // TODO add your handling code here:
        c.progressADay();
    }//GEN-LAST:event_passButton7MouseClicked

    private void passButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passButton7ActionPerformed

    private void outButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outButton7MouseClicked
        // TODO add your handling code here:
        c.isLoggedOut();
        WelcomePage w = new WelcomePage(c);
        w.setVisible(true);
    }//GEN-LAST:event_outButton7MouseClicked

    private void completedButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedButton7ActionPerformed
        // TODO add your handling code here:
        cInfoTextArea.setText(c.ceoAccess.completeTask()
                + "\n\nTasks left:\n" + c.ceoAccess.showYourTasks());
    }//GEN-LAST:event_completedButton7ActionPerformed

    private void tasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksButtonActionPerformed
        // TODO add your handling code here:
        cInfoTextArea.setText(c.ceoAccess.showYourTasks());
    }//GEN-LAST:event_tasksButtonActionPerformed

    private void hierarchyBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hierarchyBTNActionPerformed
        // TODO add your handling code here:
        cInfoTextArea.setText(c.ceoAccess.ShowCompanyHierarchy());
    }//GEN-LAST:event_hierarchyBTNActionPerformed

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        // TODO add your handling code here:
        cInfoTextArea.setText(c.ceoAccess.showOwn());
    }//GEN-LAST:event_detailsButtonActionPerformed

    private void kickbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kickbuttonActionPerformed
        // TODO add your handling code here:
        String ename = mnameField.getText();

        try {
            if (c.company.findNode(ename).getData().getName() == null) {
                throw new NullPointerException("No manager with such name.");
            }
            String newname = newNameField.getText();
            String role = newRoleField.getText();
            String dep = newDepField.getText();
            Double salary = Double.valueOf(newSalField.getText());
            if(salary<0){
            throw new NumberFormatException ( "Please enter a valid salary.");
        }
            String pass = newPassField.getText();
            Employee e = new Employee(newname, role, dep, salary, pass);
            c.ceoAccess.FireManager(ename, e);
            ceTextArea.setText("Manager fired and replaced successfully!\n\nNew manager:\n" + e.toString());

        } catch (NullPointerException e) {
            ceTextArea.setText("No manager with such name.");
        }catch (NumberFormatException e) {
            ceTextArea.setText("Please enter a valid input (salary or password)\npassword should be equal to or more than 8 characters");
        }
    }//GEN-LAST:event_kickbuttonActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        String newname = newNameField.getText();
        String role = newRoleField.getText();
        String dep = newDepField.getText();
       
        try{
        Double salary = Double.valueOf(newSalField.getText());
        if(salary<0){
            throw new NumberFormatException ( "Please enter a valid salary.");
        }
        String pass = newPassField.getText();
        Employee e = new Employee(newname, role, dep, salary, pass);
        c.ceoAccess.AddManager(e);
        ceTextArea.setText("Manager added suscessfly! \n" + e.toString());
        }catch(NullPointerException e){
             ceTextArea.setText("Please enter informations.");
        }catch (NumberFormatException e) {
            ceTextArea.setText("Please enter a valid input (salary or password)\npassword should be equal to or more than 8 characters");
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void mnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnameFieldActionPerformed

    private void showDlgBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDlgBTNActionPerformed
        // TODO add your handling code here:
        String ename = mnameField.getText();

        try {
            if (c.company.findNode(ename).getData().getName() == null) {
                throw new NullPointerException("No manager with such name.");
            }
            ctasksTextArea.setText(c.ceoAccess.ShowManagerDelegatedTasks(ename));
        } catch (NullPointerException e) {
            ctasksTextArea.setText("No manager with such name.");
        }
    }//GEN-LAST:event_showDlgBTNActionPerformed

    private void ebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebtnActionPerformed
        // TODO add your handling code here:
        String ename = mnameField.getText();

        try {
            if (c.company.findNode(ename).getData().getName() == null) {
                throw new NullPointerException("No manager with such name.");
            }
            ctasksTextArea.setText(c.ceoAccess.ShowManagerEmployees(ename));
        } catch (NullPointerException e) {
            ctasksTextArea.setText("No manager with such name.");
        }
    }//GEN-LAST:event_ebtnActionPerformed

    private void newRoleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newRoleFieldActionPerformed

    private void newSalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSalFieldActionPerformed

    private void titleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleBTNActionPerformed

    private void dateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateBTNActionPerformed

    private void SendBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBTNActionPerformed
        // TODO add your handling code here:
        String ename = mnameField.getText();
        String title = titleBTN.getText();
        String date = dateBTN.getText();
        
        String[] dates = date.split("-");
        try {
            if (c.company.findNode(ename).getData().getName() == null) {
                throw new NullPointerException("No manager with such name.");
            }

            int year = Integer.parseInt(dates[0]);
            int month = Integer.parseInt(dates[1]);
            int day = Integer.parseInt(dates[2]);
            Date dueDate = new Date(year, month - 1, day);
            Task task = new Task(title, dueDate);
            c.ceoAccess.SendTaskToManager(ename, task);
            ceTextArea.setText(c.ceoAccess.ShowManagerTasks(ename));

        } catch (NullPointerException e) {
            ceTextArea.setText("No manager with such name.");
        } catch (NumberFormatException e) {
            ceTextArea.setText("Please enter a valid date.");
        }

    }//GEN-LAST:event_SendBTNActionPerformed

    private void dlgBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlgBTNActionPerformed
        // TODO add your handling code here:
        cInfoTextArea.setText(c.ceoAccess.showDelegatedTasks());
    }//GEN-LAST:event_dlgBTNActionPerformed

    private void mtasksbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtasksbtnActionPerformed
        // TODO add your handling code here:
        String ename = mnameField.getText();

        try {
            if (c.company.findNode(ename).getData().getName() == null) {
                throw new NullPointerException("No manager with such name.");
            }
            ctasksTextArea.setText(c.ceoAccess.ShowManagerTasks(ename));
        } catch (NullPointerException e) {
            ctasksTextArea.setText("No manager with such name.");
        }
    }//GEN-LAST:event_mtasksbtnActionPerformed

    private void mdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mdetailsbtnActionPerformed
        // TODO add your handling code here:
        String ename = mnameField.getText();

        try {
            if (c.company.findNode(ename).getData().getName() == null) {
                throw new NullPointerException("No manager with such name.");
            }
            ctasksTextArea.setText(c.ceoAccess.ShowManager(ename));
        } catch (NullPointerException e) {
            ctasksTextArea.setText("No manager with such name.");
        }
    }//GEN-LAST:event_mdetailsbtnActionPerformed

    private void getdlgbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdlgbtnActionPerformed
        // TODO add your handling code here:
        String ename = mnameField.getText();

        try {
            if (c.company.findNode(ename).getData().getName() == null) {
                throw new NullPointerException("No manager with such name.");
            }
            c.ceoAccess.getAllManagerDelegatedTasks(ename);
            ctasksTextArea.setText(c.ceoAccess.showDelegatedTasks());
        } catch (NullPointerException e) {
            ctasksTextArea.setText("No manager with such name.");
        }
    }//GEN-LAST:event_getdlgbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ceo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ceo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ceo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ceo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ceo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendBTN;
    private javax.swing.JButton addBTN;
    private javax.swing.JTextArea cInfoTextArea;
    private javax.swing.JTextArea ceTextArea;
    private javax.swing.JButton completedButton7;
    private javax.swing.JTextArea ctasksTextArea;
    private javax.swing.JTextField dateBTN;
    private javax.swing.JButton detailsButton;
    private javax.swing.JButton dlgBTN;
    private javax.swing.JButton ebtn;
    private javax.swing.JButton getdlgbtn;
    private javax.swing.JButton hierarchyBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JButton kickbutton;
    private javax.swing.JButton mdetailsbtn;
    private javax.swing.JTextField mnameField;
    private javax.swing.JButton mtasksbtn;
    private javax.swing.JPanel nameFielf7;
    private javax.swing.JTextField newDepField;
    private javax.swing.JTextField newNameField;
    private javax.swing.JTextField newPassField;
    private javax.swing.JTextField newRoleField;
    private javax.swing.JTextField newSalField;
    private javax.swing.JButton outButton7;
    private javax.swing.JButton passButton7;
    private javax.swing.JButton showDlgBTN;
    private javax.swing.JButton tasksButton;
    private javax.swing.JTextField titleBTN;
    // End of variables declaration//GEN-END:variables
}
