/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package WMSdataStructuresProject;

import java.util.Date;

/**
 *
 * @author User
 */
public class Manager extends javax.swing.JFrame {

    String name;
    Company c = new Company();

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
    }

    public Manager(Company c, String n) {
        this.name = n;
        initComponents();
        this.c = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameFielf = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        tasksTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        eTextArea = new javax.swing.JTextArea();
        passButton = new javax.swing.JButton();
        outButton = new javax.swing.JButton();
        completedButton = new javax.swing.JButton();
        tasksButton = new javax.swing.JButton();
        delegButton = new javax.swing.JButton();
        detailsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kickbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        enameFielf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edetailbtn = new javax.swing.JButton();
        edisplayBTN = new javax.swing.JButton();
        eTaskbtn = new javax.swing.JButton();
        newNameField = new javax.swing.JTextField();
        newRoleField = new javax.swing.JTextField();
        newDepField = new javax.swing.JTextField();
        newPassField = new javax.swing.JTextField();
        newSalField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        titleBTN = new javax.swing.JTextField();
        dateBTN = new javax.swing.JTextField();
        SendBTN = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameFielf.setBackground(new java.awt.Color(0, 102, 102));
        nameFielf.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WMSdataStructuresProject/reslogo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Aldhabi", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("WMS");

        jLabel2.setFont(new java.awt.Font("Aldhabi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welcome Manager "+name);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        InfoTextArea.setColumns(20);
        InfoTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        InfoTextArea.setRows(5);
        jScrollPane1.setViewportView(InfoTextArea);

        tasksTextArea.setColumns(20);
        tasksTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        tasksTextArea.setRows(5);
        jScrollPane3.setViewportView(tasksTextArea);

        eTextArea.setColumns(20);
        eTextArea.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        eTextArea.setRows(5);
        jScrollPane2.setViewportView(eTextArea);

        passButton.setBackground(new java.awt.Color(0, 102, 102));
        passButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passButton.setForeground(new java.awt.Color(255, 255, 255));
        passButton.setText("pass a day");
        passButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passButtonMouseClicked(evt);
            }
        });
        passButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passButtonActionPerformed(evt);
            }
        });

        outButton.setBackground(new java.awt.Color(0, 102, 102));
        outButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        outButton.setForeground(new java.awt.Color(255, 255, 255));
        outButton.setText("Log out");
        outButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outButtonMouseClicked(evt);
            }
        });

        completedButton.setBackground(new java.awt.Color(0, 102, 102));
        completedButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        completedButton.setForeground(new java.awt.Color(255, 255, 255));
        completedButton.setText("Complete current task");
        completedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(passButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(completedButton)
                .addGap(52, 52, 52)
                .addComponent(outButton)
                .addGap(52, 52, 52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passButton)
                    .addComponent(outButton)
                    .addComponent(completedButton))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        tasksButton.setBackground(new java.awt.Color(0, 153, 153));
        tasksButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tasksButton.setForeground(new java.awt.Color(255, 255, 255));
        tasksButton.setText("Tasks");
        tasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tasksButtonActionPerformed(evt);
            }
        });

        delegButton.setBackground(new java.awt.Color(0, 153, 153));
        delegButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delegButton.setForeground(new java.awt.Color(255, 255, 255));
        delegButton.setText("Show");
        delegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delegButtonActionPerformed(evt);
            }
        });

        detailsButton.setBackground(new java.awt.Color(0, 153, 153));
        detailsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        detailsButton.setForeground(new java.awt.Color(255, 255, 255));
        detailsButton.setText("Details");
        detailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informations about you:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tap to check delegated tasks:");

        kickbutton.setBackground(new java.awt.Color(0, 153, 153));
        kickbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        kickbutton.setForeground(new java.awt.Color(255, 255, 255));
        kickbutton.setText("Kick");
        kickbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kickbuttonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("List all employees under your department:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Add new employee:");

        addBTN.setBackground(new java.awt.Color(0, 153, 153));
        addBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBTN.setForeground(new java.awt.Color(255, 255, 255));
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("-----------------------------------------------------------------------------------");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-----------------------------------------------------------------------------------");

        enameFielf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameFielfActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Employee's name:");

        edetailbtn.setBackground(new java.awt.Color(0, 153, 153));
        edetailbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edetailbtn.setForeground(new java.awt.Color(255, 255, 255));
        edetailbtn.setText("Show details");
        edetailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edetailbtnActionPerformed(evt);
            }
        });

        edisplayBTN.setBackground(new java.awt.Color(0, 153, 153));
        edisplayBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        edisplayBTN.setForeground(new java.awt.Color(255, 255, 255));
        edisplayBTN.setText("Display");
        edisplayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edisplayBTNActionPerformed(evt);
            }
        });

        eTaskbtn.setBackground(new java.awt.Color(0, 153, 153));
        eTaskbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eTaskbtn.setForeground(new java.awt.Color(255, 255, 255));
        eTaskbtn.setText("Show Tasks");
        eTaskbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eTaskbtnActionPerformed(evt);
            }
        });

        newNameField.setText("enter name..");

        newRoleField.setText("enter role..");
        newRoleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoleFieldActionPerformed(evt);
            }
        });

        newDepField.setText("enter department..");

        newPassField.setText("enter password..");

        newSalField.setText("Enter salary..");
        newSalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSalFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Send task to employee:");

        titleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleBTNActionPerformed(evt);
            }
        });

        dateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateBTNActionPerformed(evt);
            }
        });

        SendBTN.setBackground(new java.awt.Color(0, 153, 153));
        SendBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SendBTN.setForeground(new java.awt.Color(255, 255, 255));
        SendBTN.setText("Send");
        SendBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBTNActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("title");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("due Date");

        javax.swing.GroupLayout nameFielfLayout = new javax.swing.GroupLayout(nameFielf);
        nameFielf.setLayout(nameFielfLayout);
        nameFielfLayout.setHorizontalGroup(
            nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFielfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielfLayout.createSequentialGroup()
                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameFielfLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(nameFielfLayout.createSequentialGroup()
                                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(nameFielfLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(nameFielfLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(enameFielf, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(nameFielfLayout.createSequentialGroup()
                                                .addComponent(kickbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(nameFielfLayout.createSequentialGroup()
                                                        .addComponent(eTaskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(edetailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielfLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(12, 12, 12)
                                .addComponent(titleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(nameFielfLayout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielfLayout.createSequentialGroup()
                                        .addComponent(dateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SendBTN)
                                        .addGap(18, 18, 18))))))
                    .addGroup(nameFielfLayout.createSequentialGroup()
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielfLayout.createSequentialGroup()
                                .addContainerGap(5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielfLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielfLayout.createSequentialGroup()
                                                .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(newRoleField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(newDepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nameFielfLayout.createSequentialGroup()
                                                .addComponent(newSalField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(64, 64, 64)))
                                        .addGap(23, 23, 23))
                                    .addGroup(nameFielfLayout.createSequentialGroup()
                                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGap(39, 39, 39)
                                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addBTN, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(edisplayBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(nameFielfLayout.createSequentialGroup()
                                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(nameFielfLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(nameFielfLayout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(36, 36, 36)
                                                .addComponent(delegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(nameFielfLayout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(detailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(tasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(nameFielfLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        nameFielfLayout.setVerticalGroup(
            nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameFielfLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)))
                .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nameFielfLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(nameFielfLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(detailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(delegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newRoleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newDepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(newPassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newSalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(addBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edisplayBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(enameFielf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kickbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eTaskbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edetailbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(nameFielfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(titleBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendBTN)
                            .addComponent(dateBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameFielf, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameFielf, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passButtonMouseClicked
        // TODO add your handling code here:
        c.progressADay();
    }//GEN-LAST:event_passButtonMouseClicked

    private void passButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passButtonActionPerformed

    private void outButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outButtonMouseClicked
        // TODO add your handling code here:
        c.isLoggedOut();
        WelcomePage w = new WelcomePage(c);
        w.setVisible(true);
    }//GEN-LAST:event_outButtonMouseClicked

    private void detailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsButtonActionPerformed
        // TODO add your handling code here:
        InfoTextArea.setText(c.managerAccess.ShowOwn());
    }//GEN-LAST:event_detailsButtonActionPerformed

    private void tasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tasksButtonActionPerformed
        // TODO add your handling code here:
        InfoTextArea.setText(c.managerAccess.showYourTasks());
    }//GEN-LAST:event_tasksButtonActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        
        String newname = newNameField.getText();
        String role = newRoleField.getText();
        String dep = newDepField.getText();
        try{
        Double salary = Double.valueOf(newSalField.getText());
        if(salary<0){
            throw new NumberFormatException ( "Please enter a valid input (salary or password)");
        }
        String pass = newPassField.getText();
        Employee e = new Employee(newname, role, dep, salary, pass);
        c.managerAccess.addEmployee(e);
        tasksTextArea.setText("Employee added suscessfly! \n" + e.toString());
        } catch (NullPointerException e) {
            tasksTextArea.setText("please add informations.");
        } catch (NumberFormatException e) {
            tasksTextArea.setText("Please enter a valid input (salary or password)\npassword should be equal to or more than 8 characters");
        }
    }//GEN-LAST:event_addBTNActionPerformed

    private void enameFielfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameFielfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameFielfActionPerformed

    private void kickbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kickbuttonActionPerformed
        // TODO add your handling code here:
        String ename = enameFielf.getText();

        try {
            if (c.company.findNode(name).employees.search(ename) == null) {
                throw new NullPointerException("No employee with such name in your department.");
            }

            c.managerAccess.removeEmployee(ename);
            eTextArea.setText("Employee kicked successfully!");

        } catch (NullPointerException e) {
            eTextArea.setText("No employee with such name in your department.");
        } catch (NumberFormatException e) {
            tasksTextArea.setText("Please enter a valid salary.");
        }
    }//GEN-LAST:event_kickbuttonActionPerformed

    private void newRoleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newRoleFieldActionPerformed

    private void newSalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newSalFieldActionPerformed

    private void SendBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBTNActionPerformed
        // TODO add your handling code here:
        String ename = enameFielf.getText();
        String title = titleBTN.getText();
        String date = dateBTN.getText();
        String[] dates = date.split("-");
        try{
        int year = Integer.parseInt(dates[0]);
        int month = Integer.parseInt(dates[1]);
        int day = Integer.parseInt(dates[2]);
        Date dueDate = new Date(year, month-1, day);
        Task task = new Task(title, dueDate);
        c.managerAccess.sendTaskToEmployee(ename, task);
        eTextArea.setText(c.managerAccess.showEmployeeTasks(ename));
        } catch (NullPointerException e) {
            eTextArea.setText("No employee with such name.");
        } catch (NumberFormatException e) {
            eTextArea.setText("Please enter a valid date.");
        }
    }//GEN-LAST:event_SendBTNActionPerformed

    private void dateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateBTNActionPerformed

    private void titleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleBTNActionPerformed

    private void delegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delegButtonActionPerformed
        // TODO add your handling code here:
        InfoTextArea.setText(c.managerAccess.showDelegatedTasks());
    }//GEN-LAST:event_delegButtonActionPerformed

    private void completedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completedButtonActionPerformed
        // TODO add your handling code here:
        tasksTextArea.setText(c.managerAccess.completeTask()
                + "\n" + c.managerAccess.showYourTasks());
    }//GEN-LAST:event_completedButtonActionPerformed

    private void edisplayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edisplayBTNActionPerformed
        // TODO add your handling code here:
        try{
        tasksTextArea.setText(c.managerAccess.showEmployees());
        }catch (NullPointerException e) {
            tasksTextArea.setText("You don't have employees under your department yet.");
        }

        
    }//GEN-LAST:event_edisplayBTNActionPerformed

    private void eTaskbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eTaskbtnActionPerformed
        // TODO add your handling code here:
        String ename = enameFielf.getText();

        try {
            if (c.company.findNode(name).employees.search(ename) == null) {
                throw new NullPointerException("No employee with such name in your department.");
            }
            eTextArea.setText(c.managerAccess.showEmployeeTasks(ename));
        } catch (NullPointerException e) {
            eTextArea.setText("No employee with such name in your department.");
        }

    }//GEN-LAST:event_eTaskbtnActionPerformed

    private void edetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edetailbtnActionPerformed
        // TODO add your handling code here:
        String ename = enameFielf.getText();

        try {
            if (c.company.findNode(name).employees.search(ename) == null) {
                throw new NullPointerException("No employee with such name in your department.");
            }
            eTextArea.setText(c.managerAccess.showEmployee(ename));
        } catch (NullPointerException e) {
            eTextArea.setText("No employee with such name in your department.");
        }
    }//GEN-LAST:event_edetailbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InfoTextArea;
    private javax.swing.JButton SendBTN;
    private javax.swing.JButton addBTN;
    private javax.swing.JButton completedButton;
    private javax.swing.JTextField dateBTN;
    private javax.swing.JButton delegButton;
    private javax.swing.JButton detailsButton;
    private javax.swing.JButton eTaskbtn;
    private javax.swing.JTextArea eTextArea;
    private javax.swing.JButton edetailbtn;
    private javax.swing.JButton edisplayBTN;
    private javax.swing.JTextField enameFielf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kickbutton;
    private javax.swing.JPanel nameFielf;
    private javax.swing.JTextField newDepField;
    private javax.swing.JTextField newNameField;
    private javax.swing.JTextField newPassField;
    private javax.swing.JTextField newRoleField;
    private javax.swing.JTextField newSalField;
    private javax.swing.JButton outButton;
    private javax.swing.JButton passButton;
    private javax.swing.JButton tasksButton;
    private javax.swing.JTextArea tasksTextArea;
    private javax.swing.JTextField titleBTN;
    // End of variables declaration//GEN-END:variables
}
